// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.2
// source: download/proto/musicdl.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Plan item type
type PlanItemType int32

const (
	PlanItemType_PLAN_ITEM_TYPE_UNSPECIFIED PlanItemType = 0
	PlanItemType_PLAN_ITEM_TYPE_TRACK       PlanItemType = 1
	PlanItemType_PLAN_ITEM_TYPE_ALBUM       PlanItemType = 2
	PlanItemType_PLAN_ITEM_TYPE_ARTIST      PlanItemType = 3
	PlanItemType_PLAN_ITEM_TYPE_PLAYLIST    PlanItemType = 4
	PlanItemType_PLAN_ITEM_TYPE_M3U         PlanItemType = 5
)

// Enum value maps for PlanItemType.
var (
	PlanItemType_name = map[int32]string{
		0: "PLAN_ITEM_TYPE_UNSPECIFIED",
		1: "PLAN_ITEM_TYPE_TRACK",
		2: "PLAN_ITEM_TYPE_ALBUM",
		3: "PLAN_ITEM_TYPE_ARTIST",
		4: "PLAN_ITEM_TYPE_PLAYLIST",
		5: "PLAN_ITEM_TYPE_M3U",
	}
	PlanItemType_value = map[string]int32{
		"PLAN_ITEM_TYPE_UNSPECIFIED": 0,
		"PLAN_ITEM_TYPE_TRACK":       1,
		"PLAN_ITEM_TYPE_ALBUM":       2,
		"PLAN_ITEM_TYPE_ARTIST":      3,
		"PLAN_ITEM_TYPE_PLAYLIST":    4,
		"PLAN_ITEM_TYPE_M3U":         5,
	}
)

func (x PlanItemType) Enum() *PlanItemType {
	p := new(PlanItemType)
	*p = x
	return p
}

func (x PlanItemType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (PlanItemType) Descriptor() protoreflect.EnumDescriptor {
	return file_download_proto_musicdl_proto_enumTypes[0].Descriptor()
}

func (PlanItemType) Type() protoreflect.EnumType {
	return &file_download_proto_musicdl_proto_enumTypes[0]
}

func (x PlanItemType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use PlanItemType.Descriptor instead.
func (PlanItemType) EnumDescriptor() ([]byte, []int) {
	return file_download_proto_musicdl_proto_rawDescGZIP(), []int{0}
}

// Plan item status
type PlanItemStatus int32

const (
	PlanItemStatus_PLAN_ITEM_STATUS_UNSPECIFIED PlanItemStatus = 0
	PlanItemStatus_PLAN_ITEM_STATUS_PENDING     PlanItemStatus = 1
	PlanItemStatus_PLAN_ITEM_STATUS_IN_PROGRESS PlanItemStatus = 2
	PlanItemStatus_PLAN_ITEM_STATUS_COMPLETED   PlanItemStatus = 3
	PlanItemStatus_PLAN_ITEM_STATUS_FAILED      PlanItemStatus = 4
	PlanItemStatus_PLAN_ITEM_STATUS_SKIPPED     PlanItemStatus = 5
)

// Enum value maps for PlanItemStatus.
var (
	PlanItemStatus_name = map[int32]string{
		0: "PLAN_ITEM_STATUS_UNSPECIFIED",
		1: "PLAN_ITEM_STATUS_PENDING",
		2: "PLAN_ITEM_STATUS_IN_PROGRESS",
		3: "PLAN_ITEM_STATUS_COMPLETED",
		4: "PLAN_ITEM_STATUS_FAILED",
		5: "PLAN_ITEM_STATUS_SKIPPED",
	}
	PlanItemStatus_value = map[string]int32{
		"PLAN_ITEM_STATUS_UNSPECIFIED": 0,
		"PLAN_ITEM_STATUS_PENDING":     1,
		"PLAN_ITEM_STATUS_IN_PROGRESS": 2,
		"PLAN_ITEM_STATUS_COMPLETED":   3,
		"PLAN_ITEM_STATUS_FAILED":      4,
		"PLAN_ITEM_STATUS_SKIPPED":     5,
	}
)

func (x PlanItemStatus) Enum() *PlanItemStatus {
	p := new(PlanItemStatus)
	*p = x
	return p
}

func (x PlanItemStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (PlanItemStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_download_proto_musicdl_proto_enumTypes[1].Descriptor()
}

func (PlanItemStatus) Type() protoreflect.EnumType {
	return &file_download_proto_musicdl_proto_enumTypes[1]
}

func (x PlanItemStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use PlanItemStatus.Descriptor instead.
func (PlanItemStatus) EnumDescriptor() ([]byte, []int) {
	return file_download_proto_musicdl_proto_rawDescGZIP(), []int{1}
}

// Service state
type ServiceState int32

const (
	ServiceState_SERVICE_STATE_UNSPECIFIED ServiceState = 0
	ServiceState_SERVICE_STATE_IDLE        ServiceState = 1
	ServiceState_SERVICE_STATE_RUNNING     ServiceState = 2
	ServiceState_SERVICE_STATE_STOPPING    ServiceState = 3
	ServiceState_SERVICE_STATE_ERROR       ServiceState = 4
)

// Enum value maps for ServiceState.
var (
	ServiceState_name = map[int32]string{
		0: "SERVICE_STATE_UNSPECIFIED",
		1: "SERVICE_STATE_IDLE",
		2: "SERVICE_STATE_RUNNING",
		3: "SERVICE_STATE_STOPPING",
		4: "SERVICE_STATE_ERROR",
	}
	ServiceState_value = map[string]int32{
		"SERVICE_STATE_UNSPECIFIED": 0,
		"SERVICE_STATE_IDLE":        1,
		"SERVICE_STATE_RUNNING":     2,
		"SERVICE_STATE_STOPPING":    3,
		"SERVICE_STATE_ERROR":       4,
	}
)

func (x ServiceState) Enum() *ServiceState {
	p := new(ServiceState)
	*p = x
	return p
}

func (x ServiceState) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ServiceState) Descriptor() protoreflect.EnumDescriptor {
	return file_download_proto_musicdl_proto_enumTypes[2].Descriptor()
}

func (ServiceState) Type() protoreflect.EnumType {
	return &file_download_proto_musicdl_proto_enumTypes[2]
}

func (x ServiceState) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ServiceState.Descriptor instead.
func (ServiceState) EnumDescriptor() ([]byte, []int) {
	return file_download_proto_musicdl_proto_rawDescGZIP(), []int{2}
}

// Service phase
type ServicePhase int32

const (
	ServicePhase_SERVICE_PHASE_UNSPECIFIED ServicePhase = 0
	ServicePhase_SERVICE_PHASE_IDLE        ServicePhase = 1
	ServicePhase_SERVICE_PHASE_GENERATING  ServicePhase = 2
	ServicePhase_SERVICE_PHASE_OPTIMIZING  ServicePhase = 3
	ServicePhase_SERVICE_PHASE_EXECUTING   ServicePhase = 4
	ServicePhase_SERVICE_PHASE_COMPLETED   ServicePhase = 5
	ServicePhase_SERVICE_PHASE_ERROR       ServicePhase = 6
)

// Enum value maps for ServicePhase.
var (
	ServicePhase_name = map[int32]string{
		0: "SERVICE_PHASE_UNSPECIFIED",
		1: "SERVICE_PHASE_IDLE",
		2: "SERVICE_PHASE_GENERATING",
		3: "SERVICE_PHASE_OPTIMIZING",
		4: "SERVICE_PHASE_EXECUTING",
		5: "SERVICE_PHASE_COMPLETED",
		6: "SERVICE_PHASE_ERROR",
	}
	ServicePhase_value = map[string]int32{
		"SERVICE_PHASE_UNSPECIFIED": 0,
		"SERVICE_PHASE_IDLE":        1,
		"SERVICE_PHASE_GENERATING":  2,
		"SERVICE_PHASE_OPTIMIZING":  3,
		"SERVICE_PHASE_EXECUTING":   4,
		"SERVICE_PHASE_COMPLETED":   5,
		"SERVICE_PHASE_ERROR":       6,
	}
)

func (x ServicePhase) Enum() *ServicePhase {
	p := new(ServicePhase)
	*p = x
	return p
}

func (x ServicePhase) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ServicePhase) Descriptor() protoreflect.EnumDescriptor {
	return file_download_proto_musicdl_proto_enumTypes[3].Descriptor()
}

func (ServicePhase) Type() protoreflect.EnumType {
	return &file_download_proto_musicdl_proto_enumTypes[3]
}

func (x ServicePhase) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ServicePhase.Descriptor instead.
func (ServicePhase) EnumDescriptor() ([]byte, []int) {
	return file_download_proto_musicdl_proto_rawDescGZIP(), []int{3}
}

// Health status
type HealthStatus int32

const (
	HealthStatus_HEALTH_STATUS_UNSPECIFIED HealthStatus = 0
	HealthStatus_HEALTH_STATUS_HEALTHY     HealthStatus = 1
	HealthStatus_HEALTH_STATUS_UNHEALTHY   HealthStatus = 2
	HealthStatus_HEALTH_STATUS_UNAVAILABLE HealthStatus = 3
)

// Enum value maps for HealthStatus.
var (
	HealthStatus_name = map[int32]string{
		0: "HEALTH_STATUS_UNSPECIFIED",
		1: "HEALTH_STATUS_HEALTHY",
		2: "HEALTH_STATUS_UNHEALTHY",
		3: "HEALTH_STATUS_UNAVAILABLE",
	}
	HealthStatus_value = map[string]int32{
		"HEALTH_STATUS_UNSPECIFIED": 0,
		"HEALTH_STATUS_HEALTHY":     1,
		"HEALTH_STATUS_UNHEALTHY":   2,
		"HEALTH_STATUS_UNAVAILABLE": 3,
	}
)

func (x HealthStatus) Enum() *HealthStatus {
	p := new(HealthStatus)
	*p = x
	return p
}

func (x HealthStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (HealthStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_download_proto_musicdl_proto_enumTypes[4].Descriptor()
}

func (HealthStatus) Type() protoreflect.EnumType {
	return &file_download_proto_musicdl_proto_enumTypes[4]
}

func (x HealthStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use HealthStatus.Descriptor instead.
func (HealthStatus) EnumDescriptor() ([]byte, []int) {
	return file_download_proto_musicdl_proto_rawDescGZIP(), []int{4}
}

// Readiness status
type ReadinessStatus int32

const (
	ReadinessStatus_READINESS_STATUS_UNSPECIFIED ReadinessStatus = 0
	ReadinessStatus_READINESS_STATUS_READY       ReadinessStatus = 1
	ReadinessStatus_READINESS_STATUS_NOT_READY   ReadinessStatus = 2
	ReadinessStatus_READINESS_STATUS_UNAVAILABLE ReadinessStatus = 3
)

// Enum value maps for ReadinessStatus.
var (
	ReadinessStatus_name = map[int32]string{
		0: "READINESS_STATUS_UNSPECIFIED",
		1: "READINESS_STATUS_READY",
		2: "READINESS_STATUS_NOT_READY",
		3: "READINESS_STATUS_UNAVAILABLE",
	}
	ReadinessStatus_value = map[string]int32{
		"READINESS_STATUS_UNSPECIFIED": 0,
		"READINESS_STATUS_READY":       1,
		"READINESS_STATUS_NOT_READY":   2,
		"READINESS_STATUS_UNAVAILABLE": 3,
	}
)

func (x ReadinessStatus) Enum() *ReadinessStatus {
	p := new(ReadinessStatus)
	*p = x
	return p
}

func (x ReadinessStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ReadinessStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_download_proto_musicdl_proto_enumTypes[5].Descriptor()
}

func (ReadinessStatus) Type() protoreflect.EnumType {
	return &file_download_proto_musicdl_proto_enumTypes[5]
}

func (x ReadinessStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ReadinessStatus.Descriptor instead.
func (ReadinessStatus) EnumDescriptor() ([]byte, []int) {
	return file_download_proto_musicdl_proto_rawDescGZIP(), []int{5}
}

// Log level
type LogLevel int32

const (
	LogLevel_LOG_LEVEL_UNSPECIFIED LogLevel = 0
	LogLevel_LOG_LEVEL_DEBUG       LogLevel = 1
	LogLevel_LOG_LEVEL_INFO        LogLevel = 2
	LogLevel_LOG_LEVEL_WARN        LogLevel = 3
	LogLevel_LOG_LEVEL_ERROR       LogLevel = 4
)

// Enum value maps for LogLevel.
var (
	LogLevel_name = map[int32]string{
		0: "LOG_LEVEL_UNSPECIFIED",
		1: "LOG_LEVEL_DEBUG",
		2: "LOG_LEVEL_INFO",
		3: "LOG_LEVEL_WARN",
		4: "LOG_LEVEL_ERROR",
	}
	LogLevel_value = map[string]int32{
		"LOG_LEVEL_UNSPECIFIED": 0,
		"LOG_LEVEL_DEBUG":       1,
		"LOG_LEVEL_INFO":        2,
		"LOG_LEVEL_WARN":        3,
		"LOG_LEVEL_ERROR":       4,
	}
)

func (x LogLevel) Enum() *LogLevel {
	p := new(LogLevel)
	*p = x
	return p
}

func (x LogLevel) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (LogLevel) Descriptor() protoreflect.EnumDescriptor {
	return file_download_proto_musicdl_proto_enumTypes[6].Descriptor()
}

func (LogLevel) Type() protoreflect.EnumType {
	return &file_download_proto_musicdl_proto_enumTypes[6]
}

func (x LogLevel) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use LogLevel.Descriptor instead.
func (LogLevel) EnumDescriptor() ([]byte, []int) {
	return file_download_proto_musicdl_proto_rawDescGZIP(), []int{6}
}

// Version information
type VersionInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Version       string                 `protobuf:"bytes,1,opt,name=version,proto3" json:"version,omitempty"` // Version string (e.g., "v1.2.3" or "dev")
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VersionInfo) Reset() {
	*x = VersionInfo{}
	mi := &file_download_proto_musicdl_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VersionInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VersionInfo) ProtoMessage() {}

func (x *VersionInfo) ProtoReflect() protoreflect.Message {
	mi := &file_download_proto_musicdl_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VersionInfo.ProtoReflect.Descriptor instead.
func (*VersionInfo) Descriptor() ([]byte, []int) {
	return file_download_proto_musicdl_proto_rawDescGZIP(), []int{0}
}

func (x *VersionInfo) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

// Music source entry
type MusicSource struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Url           string                 `protobuf:"bytes,2,opt,name=url,proto3" json:"url,omitempty"`
	CreateM3U     bool                   `protobuf:"varint,3,opt,name=create_m3u,json=createM3u,proto3" json:"create_m3u,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MusicSource) Reset() {
	*x = MusicSource{}
	mi := &file_download_proto_musicdl_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MusicSource) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MusicSource) ProtoMessage() {}

func (x *MusicSource) ProtoReflect() protoreflect.Message {
	mi := &file_download_proto_musicdl_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MusicSource.ProtoReflect.Descriptor instead.
func (*MusicSource) Descriptor() ([]byte, []int) {
	return file_download_proto_musicdl_proto_rawDescGZIP(), []int{1}
}

func (x *MusicSource) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *MusicSource) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

func (x *MusicSource) GetCreateM3U() bool {
	if x != nil {
		return x.CreateM3U
	}
	return false
}

// Download settings
type DownloadSettings struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Spotify API credentials
	ClientId     string `protobuf:"bytes,1,opt,name=client_id,json=clientId,proto3" json:"client_id,omitempty"`
	ClientSecret string `protobuf:"bytes,2,opt,name=client_secret,json=clientSecret,proto3" json:"client_secret,omitempty"`
	// Basic download settings
	Threads        int32    `protobuf:"varint,3,opt,name=threads,proto3" json:"threads,omitempty"`
	MaxRetries     int32    `protobuf:"varint,4,opt,name=max_retries,json=maxRetries,proto3" json:"max_retries,omitempty"`
	Format         string   `protobuf:"bytes,5,opt,name=format,proto3" json:"format,omitempty"`
	Bitrate        string   `protobuf:"bytes,6,opt,name=bitrate,proto3" json:"bitrate,omitempty"`
	Output         string   `protobuf:"bytes,7,opt,name=output,proto3" json:"output,omitempty"`
	AudioProviders []string `protobuf:"bytes,8,rep,name=audio_providers,json=audioProviders,proto3" json:"audio_providers,omitempty"`
	Overwrite      string   `protobuf:"bytes,9,opt,name=overwrite,proto3" json:"overwrite,omitempty"` // "skip", "overwrite", "metadata"
	// Cache settings
	CacheMaxSize              int32 `protobuf:"varint,10,opt,name=cache_max_size,json=cacheMaxSize,proto3" json:"cache_max_size,omitempty"`
	CacheTtl                  int32 `protobuf:"varint,11,opt,name=cache_ttl,json=cacheTtl,proto3" json:"cache_ttl,omitempty"`
	AudioSearchCacheMaxSize   int32 `protobuf:"varint,12,opt,name=audio_search_cache_max_size,json=audioSearchCacheMaxSize,proto3" json:"audio_search_cache_max_size,omitempty"`
	AudioSearchCacheTtl       int32 `protobuf:"varint,13,opt,name=audio_search_cache_ttl,json=audioSearchCacheTtl,proto3" json:"audio_search_cache_ttl,omitempty"`
	FileExistenceCacheMaxSize int32 `protobuf:"varint,14,opt,name=file_existence_cache_max_size,json=fileExistenceCacheMaxSize,proto3" json:"file_existence_cache_max_size,omitempty"`
	FileExistenceCacheTtl     int32 `protobuf:"varint,15,opt,name=file_existence_cache_ttl,json=fileExistenceCacheTtl,proto3" json:"file_existence_cache_ttl,omitempty"`
	// Spotify rate limiting settings
	SpotifyMaxRetries        int32   `protobuf:"varint,16,opt,name=spotify_max_retries,json=spotifyMaxRetries,proto3" json:"spotify_max_retries,omitempty"`
	SpotifyRetryBaseDelay    float64 `protobuf:"fixed64,17,opt,name=spotify_retry_base_delay,json=spotifyRetryBaseDelay,proto3" json:"spotify_retry_base_delay,omitempty"`
	SpotifyRetryMaxDelay     float64 `protobuf:"fixed64,18,opt,name=spotify_retry_max_delay,json=spotifyRetryMaxDelay,proto3" json:"spotify_retry_max_delay,omitempty"`
	SpotifyRateLimitEnabled  bool    `protobuf:"varint,19,opt,name=spotify_rate_limit_enabled,json=spotifyRateLimitEnabled,proto3" json:"spotify_rate_limit_enabled,omitempty"`
	SpotifyRateLimitRequests int32   `protobuf:"varint,20,opt,name=spotify_rate_limit_requests,json=spotifyRateLimitRequests,proto3" json:"spotify_rate_limit_requests,omitempty"`
	SpotifyRateLimitWindow   float64 `protobuf:"fixed64,21,opt,name=spotify_rate_limit_window,json=spotifyRateLimitWindow,proto3" json:"spotify_rate_limit_window,omitempty"`
	// Download rate limiting settings
	DownloadRateLimitEnabled  bool    `protobuf:"varint,22,opt,name=download_rate_limit_enabled,json=downloadRateLimitEnabled,proto3" json:"download_rate_limit_enabled,omitempty"`
	DownloadRateLimitRequests int32   `protobuf:"varint,23,opt,name=download_rate_limit_requests,json=downloadRateLimitRequests,proto3" json:"download_rate_limit_requests,omitempty"`
	DownloadRateLimitWindow   float64 `protobuf:"fixed64,24,opt,name=download_rate_limit_window,json=downloadRateLimitWindow,proto3" json:"download_rate_limit_window,omitempty"`
	DownloadBandwidthLimit    *int32  `protobuf:"varint,25,opt,name=download_bandwidth_limit,json=downloadBandwidthLimit,proto3,oneof" json:"download_bandwidth_limit,omitempty"` // nil = unlimited
	// Plan architecture feature flags
	PlanGenerationEnabled      bool `protobuf:"varint,26,opt,name=plan_generation_enabled,json=planGenerationEnabled,proto3" json:"plan_generation_enabled,omitempty"`
	PlanOptimizationEnabled    bool `protobuf:"varint,27,opt,name=plan_optimization_enabled,json=planOptimizationEnabled,proto3" json:"plan_optimization_enabled,omitempty"`
	PlanExecutionEnabled       bool `protobuf:"varint,28,opt,name=plan_execution_enabled,json=planExecutionEnabled,proto3" json:"plan_execution_enabled,omitempty"`
	PlanPersistenceEnabled     bool `protobuf:"varint,29,opt,name=plan_persistence_enabled,json=planPersistenceEnabled,proto3" json:"plan_persistence_enabled,omitempty"`
	PlanStatusReportingEnabled bool `protobuf:"varint,30,opt,name=plan_status_reporting_enabled,json=planStatusReportingEnabled,proto3" json:"plan_status_reporting_enabled,omitempty"`
	unknownFields              protoimpl.UnknownFields
	sizeCache                  protoimpl.SizeCache
}

func (x *DownloadSettings) Reset() {
	*x = DownloadSettings{}
	mi := &file_download_proto_musicdl_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DownloadSettings) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DownloadSettings) ProtoMessage() {}

func (x *DownloadSettings) ProtoReflect() protoreflect.Message {
	mi := &file_download_proto_musicdl_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DownloadSettings.ProtoReflect.Descriptor instead.
func (*DownloadSettings) Descriptor() ([]byte, []int) {
	return file_download_proto_musicdl_proto_rawDescGZIP(), []int{2}
}

func (x *DownloadSettings) GetClientId() string {
	if x != nil {
		return x.ClientId
	}
	return ""
}

func (x *DownloadSettings) GetClientSecret() string {
	if x != nil {
		return x.ClientSecret
	}
	return ""
}

func (x *DownloadSettings) GetThreads() int32 {
	if x != nil {
		return x.Threads
	}
	return 0
}

func (x *DownloadSettings) GetMaxRetries() int32 {
	if x != nil {
		return x.MaxRetries
	}
	return 0
}

func (x *DownloadSettings) GetFormat() string {
	if x != nil {
		return x.Format
	}
	return ""
}

func (x *DownloadSettings) GetBitrate() string {
	if x != nil {
		return x.Bitrate
	}
	return ""
}

func (x *DownloadSettings) GetOutput() string {
	if x != nil {
		return x.Output
	}
	return ""
}

func (x *DownloadSettings) GetAudioProviders() []string {
	if x != nil {
		return x.AudioProviders
	}
	return nil
}

func (x *DownloadSettings) GetOverwrite() string {
	if x != nil {
		return x.Overwrite
	}
	return ""
}

func (x *DownloadSettings) GetCacheMaxSize() int32 {
	if x != nil {
		return x.CacheMaxSize
	}
	return 0
}

func (x *DownloadSettings) GetCacheTtl() int32 {
	if x != nil {
		return x.CacheTtl
	}
	return 0
}

func (x *DownloadSettings) GetAudioSearchCacheMaxSize() int32 {
	if x != nil {
		return x.AudioSearchCacheMaxSize
	}
	return 0
}

func (x *DownloadSettings) GetAudioSearchCacheTtl() int32 {
	if x != nil {
		return x.AudioSearchCacheTtl
	}
	return 0
}

func (x *DownloadSettings) GetFileExistenceCacheMaxSize() int32 {
	if x != nil {
		return x.FileExistenceCacheMaxSize
	}
	return 0
}

func (x *DownloadSettings) GetFileExistenceCacheTtl() int32 {
	if x != nil {
		return x.FileExistenceCacheTtl
	}
	return 0
}

func (x *DownloadSettings) GetSpotifyMaxRetries() int32 {
	if x != nil {
		return x.SpotifyMaxRetries
	}
	return 0
}

func (x *DownloadSettings) GetSpotifyRetryBaseDelay() float64 {
	if x != nil {
		return x.SpotifyRetryBaseDelay
	}
	return 0
}

func (x *DownloadSettings) GetSpotifyRetryMaxDelay() float64 {
	if x != nil {
		return x.SpotifyRetryMaxDelay
	}
	return 0
}

func (x *DownloadSettings) GetSpotifyRateLimitEnabled() bool {
	if x != nil {
		return x.SpotifyRateLimitEnabled
	}
	return false
}

func (x *DownloadSettings) GetSpotifyRateLimitRequests() int32 {
	if x != nil {
		return x.SpotifyRateLimitRequests
	}
	return 0
}

func (x *DownloadSettings) GetSpotifyRateLimitWindow() float64 {
	if x != nil {
		return x.SpotifyRateLimitWindow
	}
	return 0
}

func (x *DownloadSettings) GetDownloadRateLimitEnabled() bool {
	if x != nil {
		return x.DownloadRateLimitEnabled
	}
	return false
}

func (x *DownloadSettings) GetDownloadRateLimitRequests() int32 {
	if x != nil {
		return x.DownloadRateLimitRequests
	}
	return 0
}

func (x *DownloadSettings) GetDownloadRateLimitWindow() float64 {
	if x != nil {
		return x.DownloadRateLimitWindow
	}
	return 0
}

func (x *DownloadSettings) GetDownloadBandwidthLimit() int32 {
	if x != nil && x.DownloadBandwidthLimit != nil {
		return *x.DownloadBandwidthLimit
	}
	return 0
}

func (x *DownloadSettings) GetPlanGenerationEnabled() bool {
	if x != nil {
		return x.PlanGenerationEnabled
	}
	return false
}

func (x *DownloadSettings) GetPlanOptimizationEnabled() bool {
	if x != nil {
		return x.PlanOptimizationEnabled
	}
	return false
}

func (x *DownloadSettings) GetPlanExecutionEnabled() bool {
	if x != nil {
		return x.PlanExecutionEnabled
	}
	return false
}

func (x *DownloadSettings) GetPlanPersistenceEnabled() bool {
	if x != nil {
		return x.PlanPersistenceEnabled
	}
	return false
}

func (x *DownloadSettings) GetPlanStatusReportingEnabled() bool {
	if x != nil {
		return x.PlanStatusReportingEnabled
	}
	return false
}

// UI settings
type UISettings struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	HistoryPath      string                 `protobuf:"bytes,1,opt,name=history_path,json=historyPath,proto3" json:"history_path,omitempty"`
	HistoryRetention int32                  `protobuf:"varint,2,opt,name=history_retention,json=historyRetention,proto3" json:"history_retention,omitempty"`
	SnapshotInterval int32                  `protobuf:"varint,3,opt,name=snapshot_interval,json=snapshotInterval,proto3" json:"snapshot_interval,omitempty"`
	LogPath          string                 `protobuf:"bytes,4,opt,name=log_path,json=logPath,proto3" json:"log_path,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *UISettings) Reset() {
	*x = UISettings{}
	mi := &file_download_proto_musicdl_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UISettings) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UISettings) ProtoMessage() {}

func (x *UISettings) ProtoReflect() protoreflect.Message {
	mi := &file_download_proto_musicdl_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UISettings.ProtoReflect.Descriptor instead.
func (*UISettings) Descriptor() ([]byte, []int) {
	return file_download_proto_musicdl_proto_rawDescGZIP(), []int{3}
}

func (x *UISettings) GetHistoryPath() string {
	if x != nil {
		return x.HistoryPath
	}
	return ""
}

func (x *UISettings) GetHistoryRetention() int32 {
	if x != nil {
		return x.HistoryRetention
	}
	return 0
}

func (x *UISettings) GetSnapshotInterval() int32 {
	if x != nil {
		return x.SnapshotInterval
	}
	return 0
}

func (x *UISettings) GetLogPath() string {
	if x != nil {
		return x.LogPath
	}
	return ""
}

// Complete configuration
type Config struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Version       string                 `protobuf:"bytes,1,opt,name=version,proto3" json:"version,omitempty"` // Config version (e.g., "1.2")
	Download      *DownloadSettings      `protobuf:"bytes,2,opt,name=download,proto3" json:"download,omitempty"`
	Ui            *UISettings            `protobuf:"bytes,3,opt,name=ui,proto3" json:"ui,omitempty"`
	Songs         []*MusicSource         `protobuf:"bytes,4,rep,name=songs,proto3" json:"songs,omitempty"`
	Artists       []*MusicSource         `protobuf:"bytes,5,rep,name=artists,proto3" json:"artists,omitempty"`
	Playlists     []*MusicSource         `protobuf:"bytes,6,rep,name=playlists,proto3" json:"playlists,omitempty"`
	Albums        []*MusicSource         `protobuf:"bytes,7,rep,name=albums,proto3" json:"albums,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Config) Reset() {
	*x = Config{}
	mi := &file_download_proto_musicdl_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Config) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Config) ProtoMessage() {}

func (x *Config) ProtoReflect() protoreflect.Message {
	mi := &file_download_proto_musicdl_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Config.ProtoReflect.Descriptor instead.
func (*Config) Descriptor() ([]byte, []int) {
	return file_download_proto_musicdl_proto_rawDescGZIP(), []int{4}
}

func (x *Config) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *Config) GetDownload() *DownloadSettings {
	if x != nil {
		return x.Download
	}
	return nil
}

func (x *Config) GetUi() *UISettings {
	if x != nil {
		return x.Ui
	}
	return nil
}

func (x *Config) GetSongs() []*MusicSource {
	if x != nil {
		return x.Songs
	}
	return nil
}

func (x *Config) GetArtists() []*MusicSource {
	if x != nil {
		return x.Artists
	}
	return nil
}

func (x *Config) GetPlaylists() []*MusicSource {
	if x != nil {
		return x.Playlists
	}
	return nil
}

func (x *Config) GetAlbums() []*MusicSource {
	if x != nil {
		return x.Albums
	}
	return nil
}

// Plan item
type PlanItem struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ItemId        string                 `protobuf:"bytes,1,opt,name=item_id,json=itemId,proto3" json:"item_id,omitempty"`
	ItemType      PlanItemType           `protobuf:"varint,2,opt,name=item_type,json=itemType,proto3,enum=proto.PlanItemType" json:"item_type,omitempty"`
	SpotifyId     string                 `protobuf:"bytes,3,opt,name=spotify_id,json=spotifyId,proto3" json:"spotify_id,omitempty"`
	SpotifyUrl    string                 `protobuf:"bytes,4,opt,name=spotify_url,json=spotifyUrl,proto3" json:"spotify_url,omitempty"`
	YoutubeUrl    string                 `protobuf:"bytes,5,opt,name=youtube_url,json=youtubeUrl,proto3" json:"youtube_url,omitempty"`
	ParentId      string                 `protobuf:"bytes,6,opt,name=parent_id,json=parentId,proto3" json:"parent_id,omitempty"`
	ChildIds      []string               `protobuf:"bytes,7,rep,name=child_ids,json=childIds,proto3" json:"child_ids,omitempty"`
	Name          string                 `protobuf:"bytes,8,opt,name=name,proto3" json:"name,omitempty"`
	Metadata      map[string]string      `protobuf:"bytes,9,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"` // Simplified: all values as strings
	Status        PlanItemStatus         `protobuf:"varint,10,opt,name=status,proto3,enum=proto.PlanItemStatus" json:"status,omitempty"`
	Error         string                 `protobuf:"bytes,11,opt,name=error,proto3" json:"error,omitempty"`
	FilePath      string                 `protobuf:"bytes,12,opt,name=file_path,json=filePath,proto3" json:"file_path,omitempty"`
	CreatedAt     int64                  `protobuf:"varint,13,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`             // Unix timestamp
	StartedAt     *int64                 `protobuf:"varint,14,opt,name=started_at,json=startedAt,proto3,oneof" json:"started_at,omitempty"`       // Unix timestamp
	CompletedAt   *int64                 `protobuf:"varint,15,opt,name=completed_at,json=completedAt,proto3,oneof" json:"completed_at,omitempty"` // Unix timestamp
	Progress      float64                `protobuf:"fixed64,16,opt,name=progress,proto3" json:"progress,omitempty"`                               // 0.0 to 1.0
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PlanItem) Reset() {
	*x = PlanItem{}
	mi := &file_download_proto_musicdl_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PlanItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PlanItem) ProtoMessage() {}

func (x *PlanItem) ProtoReflect() protoreflect.Message {
	mi := &file_download_proto_musicdl_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PlanItem.ProtoReflect.Descriptor instead.
func (*PlanItem) Descriptor() ([]byte, []int) {
	return file_download_proto_musicdl_proto_rawDescGZIP(), []int{5}
}

func (x *PlanItem) GetItemId() string {
	if x != nil {
		return x.ItemId
	}
	return ""
}

func (x *PlanItem) GetItemType() PlanItemType {
	if x != nil {
		return x.ItemType
	}
	return PlanItemType_PLAN_ITEM_TYPE_UNSPECIFIED
}

func (x *PlanItem) GetSpotifyId() string {
	if x != nil {
		return x.SpotifyId
	}
	return ""
}

func (x *PlanItem) GetSpotifyUrl() string {
	if x != nil {
		return x.SpotifyUrl
	}
	return ""
}

func (x *PlanItem) GetYoutubeUrl() string {
	if x != nil {
		return x.YoutubeUrl
	}
	return ""
}

func (x *PlanItem) GetParentId() string {
	if x != nil {
		return x.ParentId
	}
	return ""
}

func (x *PlanItem) GetChildIds() []string {
	if x != nil {
		return x.ChildIds
	}
	return nil
}

func (x *PlanItem) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *PlanItem) GetMetadata() map[string]string {
	if x != nil {
		return x.Metadata
	}
	return nil
}

func (x *PlanItem) GetStatus() PlanItemStatus {
	if x != nil {
		return x.Status
	}
	return PlanItemStatus_PLAN_ITEM_STATUS_UNSPECIFIED
}

func (x *PlanItem) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

func (x *PlanItem) GetFilePath() string {
	if x != nil {
		return x.FilePath
	}
	return ""
}

func (x *PlanItem) GetCreatedAt() int64 {
	if x != nil {
		return x.CreatedAt
	}
	return 0
}

func (x *PlanItem) GetStartedAt() int64 {
	if x != nil && x.StartedAt != nil {
		return *x.StartedAt
	}
	return 0
}

func (x *PlanItem) GetCompletedAt() int64 {
	if x != nil && x.CompletedAt != nil {
		return *x.CompletedAt
	}
	return 0
}

func (x *PlanItem) GetProgress() float64 {
	if x != nil {
		return x.Progress
	}
	return 0
}

// Start download request
type StartDownloadRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Config        *Config                `protobuf:"bytes,1,opt,name=config,proto3" json:"config,omitempty"`
	PlanPath      string                 `protobuf:"bytes,2,opt,name=plan_path,json=planPath,proto3" json:"plan_path,omitempty"`
	LogPath       string                 `protobuf:"bytes,3,opt,name=log_path,json=logPath,proto3" json:"log_path,omitempty"`
	ClientVersion *VersionInfo           `protobuf:"bytes,4,opt,name=client_version,json=clientVersion,proto3" json:"client_version,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StartDownloadRequest) Reset() {
	*x = StartDownloadRequest{}
	mi := &file_download_proto_musicdl_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StartDownloadRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StartDownloadRequest) ProtoMessage() {}

func (x *StartDownloadRequest) ProtoReflect() protoreflect.Message {
	mi := &file_download_proto_musicdl_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StartDownloadRequest.ProtoReflect.Descriptor instead.
func (*StartDownloadRequest) Descriptor() ([]byte, []int) {
	return file_download_proto_musicdl_proto_rawDescGZIP(), []int{6}
}

func (x *StartDownloadRequest) GetConfig() *Config {
	if x != nil {
		return x.Config
	}
	return nil
}

func (x *StartDownloadRequest) GetPlanPath() string {
	if x != nil {
		return x.PlanPath
	}
	return ""
}

func (x *StartDownloadRequest) GetLogPath() string {
	if x != nil {
		return x.LogPath
	}
	return ""
}

func (x *StartDownloadRequest) GetClientVersion() *VersionInfo {
	if x != nil {
		return x.ClientVersion
	}
	return nil
}

// Start download response
type StartDownloadResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	ErrorMessage  string                 `protobuf:"bytes,2,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"`
	ServerVersion *VersionInfo           `protobuf:"bytes,3,opt,name=server_version,json=serverVersion,proto3" json:"server_version,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StartDownloadResponse) Reset() {
	*x = StartDownloadResponse{}
	mi := &file_download_proto_musicdl_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StartDownloadResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StartDownloadResponse) ProtoMessage() {}

func (x *StartDownloadResponse) ProtoReflect() protoreflect.Message {
	mi := &file_download_proto_musicdl_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StartDownloadResponse.ProtoReflect.Descriptor instead.
func (*StartDownloadResponse) Descriptor() ([]byte, []int) {
	return file_download_proto_musicdl_proto_rawDescGZIP(), []int{7}
}

func (x *StartDownloadResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *StartDownloadResponse) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

func (x *StartDownloadResponse) GetServerVersion() *VersionInfo {
	if x != nil {
		return x.ServerVersion
	}
	return nil
}

// Stop download request
type StopDownloadRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ClientVersion *VersionInfo           `protobuf:"bytes,1,opt,name=client_version,json=clientVersion,proto3" json:"client_version,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StopDownloadRequest) Reset() {
	*x = StopDownloadRequest{}
	mi := &file_download_proto_musicdl_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StopDownloadRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StopDownloadRequest) ProtoMessage() {}

func (x *StopDownloadRequest) ProtoReflect() protoreflect.Message {
	mi := &file_download_proto_musicdl_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StopDownloadRequest.ProtoReflect.Descriptor instead.
func (*StopDownloadRequest) Descriptor() ([]byte, []int) {
	return file_download_proto_musicdl_proto_rawDescGZIP(), []int{8}
}

func (x *StopDownloadRequest) GetClientVersion() *VersionInfo {
	if x != nil {
		return x.ClientVersion
	}
	return nil
}

// Stop download response
type StopDownloadResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	ErrorMessage  string                 `protobuf:"bytes,2,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"`
	ServerVersion *VersionInfo           `protobuf:"bytes,3,opt,name=server_version,json=serverVersion,proto3" json:"server_version,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StopDownloadResponse) Reset() {
	*x = StopDownloadResponse{}
	mi := &file_download_proto_musicdl_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StopDownloadResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StopDownloadResponse) ProtoMessage() {}

func (x *StopDownloadResponse) ProtoReflect() protoreflect.Message {
	mi := &file_download_proto_musicdl_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StopDownloadResponse.ProtoReflect.Descriptor instead.
func (*StopDownloadResponse) Descriptor() ([]byte, []int) {
	return file_download_proto_musicdl_proto_rawDescGZIP(), []int{9}
}

func (x *StopDownloadResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *StopDownloadResponse) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

func (x *StopDownloadResponse) GetServerVersion() *VersionInfo {
	if x != nil {
		return x.ServerVersion
	}
	return nil
}

// Get status request
type GetStatusRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ClientVersion *VersionInfo           `protobuf:"bytes,1,opt,name=client_version,json=clientVersion,proto3" json:"client_version,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetStatusRequest) Reset() {
	*x = GetStatusRequest{}
	mi := &file_download_proto_musicdl_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetStatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetStatusRequest) ProtoMessage() {}

func (x *GetStatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_download_proto_musicdl_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetStatusRequest.ProtoReflect.Descriptor instead.
func (*GetStatusRequest) Descriptor() ([]byte, []int) {
	return file_download_proto_musicdl_proto_rawDescGZIP(), []int{10}
}

func (x *GetStatusRequest) GetClientVersion() *VersionInfo {
	if x != nil {
		return x.ClientVersion
	}
	return nil
}

// Get status response
type GetStatusResponse struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	State              ServiceState           `protobuf:"varint,1,opt,name=state,proto3,enum=proto.ServiceState" json:"state,omitempty"`
	Phase              ServicePhase           `protobuf:"varint,2,opt,name=phase,proto3,enum=proto.ServicePhase" json:"phase,omitempty"`
	ErrorMessage       string                 `protobuf:"bytes,3,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"`
	StartedAt          int64                  `protobuf:"varint,4,opt,name=started_at,json=startedAt,proto3" json:"started_at,omitempty"`             // Unix timestamp, 0 if not started
	CompletedAt        *int64                 `protobuf:"varint,5,opt,name=completed_at,json=completedAt,proto3,oneof" json:"completed_at,omitempty"` // Unix timestamp
	ProgressPercentage float64                `protobuf:"fixed64,6,opt,name=progress_percentage,json=progressPercentage,proto3" json:"progress_percentage,omitempty"`
	TotalItems         int32                  `protobuf:"varint,7,opt,name=total_items,json=totalItems,proto3" json:"total_items,omitempty"`
	CompletedItems     int32                  `protobuf:"varint,8,opt,name=completed_items,json=completedItems,proto3" json:"completed_items,omitempty"`
	FailedItems        int32                  `protobuf:"varint,9,opt,name=failed_items,json=failedItems,proto3" json:"failed_items,omitempty"`
	PendingItems       int32                  `protobuf:"varint,10,opt,name=pending_items,json=pendingItems,proto3" json:"pending_items,omitempty"`
	InProgressItems    int32                  `protobuf:"varint,11,opt,name=in_progress_items,json=inProgressItems,proto3" json:"in_progress_items,omitempty"`
	ServerVersion      *VersionInfo           `protobuf:"bytes,12,opt,name=server_version,json=serverVersion,proto3" json:"server_version,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *GetStatusResponse) Reset() {
	*x = GetStatusResponse{}
	mi := &file_download_proto_musicdl_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetStatusResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetStatusResponse) ProtoMessage() {}

func (x *GetStatusResponse) ProtoReflect() protoreflect.Message {
	mi := &file_download_proto_musicdl_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetStatusResponse.ProtoReflect.Descriptor instead.
func (*GetStatusResponse) Descriptor() ([]byte, []int) {
	return file_download_proto_musicdl_proto_rawDescGZIP(), []int{11}
}

func (x *GetStatusResponse) GetState() ServiceState {
	if x != nil {
		return x.State
	}
	return ServiceState_SERVICE_STATE_UNSPECIFIED
}

func (x *GetStatusResponse) GetPhase() ServicePhase {
	if x != nil {
		return x.Phase
	}
	return ServicePhase_SERVICE_PHASE_UNSPECIFIED
}

func (x *GetStatusResponse) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

func (x *GetStatusResponse) GetStartedAt() int64 {
	if x != nil {
		return x.StartedAt
	}
	return 0
}

func (x *GetStatusResponse) GetCompletedAt() int64 {
	if x != nil && x.CompletedAt != nil {
		return *x.CompletedAt
	}
	return 0
}

func (x *GetStatusResponse) GetProgressPercentage() float64 {
	if x != nil {
		return x.ProgressPercentage
	}
	return 0
}

func (x *GetStatusResponse) GetTotalItems() int32 {
	if x != nil {
		return x.TotalItems
	}
	return 0
}

func (x *GetStatusResponse) GetCompletedItems() int32 {
	if x != nil {
		return x.CompletedItems
	}
	return 0
}

func (x *GetStatusResponse) GetFailedItems() int32 {
	if x != nil {
		return x.FailedItems
	}
	return 0
}

func (x *GetStatusResponse) GetPendingItems() int32 {
	if x != nil {
		return x.PendingItems
	}
	return 0
}

func (x *GetStatusResponse) GetInProgressItems() int32 {
	if x != nil {
		return x.InProgressItems
	}
	return 0
}

func (x *GetStatusResponse) GetServerVersion() *VersionInfo {
	if x != nil {
		return x.ServerVersion
	}
	return nil
}

// Plan item filters
type PlanItemFilters struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        []PlanItemStatus       `protobuf:"varint,1,rep,packed,name=status,proto3,enum=proto.PlanItemStatus" json:"status,omitempty"`
	Type          []PlanItemType         `protobuf:"varint,2,rep,packed,name=type,proto3,enum=proto.PlanItemType" json:"type,omitempty"`
	Search        string                 `protobuf:"bytes,3,opt,name=search,proto3" json:"search,omitempty"` // Search term for name/URL
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PlanItemFilters) Reset() {
	*x = PlanItemFilters{}
	mi := &file_download_proto_musicdl_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PlanItemFilters) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PlanItemFilters) ProtoMessage() {}

func (x *PlanItemFilters) ProtoReflect() protoreflect.Message {
	mi := &file_download_proto_musicdl_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PlanItemFilters.ProtoReflect.Descriptor instead.
func (*PlanItemFilters) Descriptor() ([]byte, []int) {
	return file_download_proto_musicdl_proto_rawDescGZIP(), []int{12}
}

func (x *PlanItemFilters) GetStatus() []PlanItemStatus {
	if x != nil {
		return x.Status
	}
	return nil
}

func (x *PlanItemFilters) GetType() []PlanItemType {
	if x != nil {
		return x.Type
	}
	return nil
}

func (x *PlanItemFilters) GetSearch() string {
	if x != nil {
		return x.Search
	}
	return ""
}

// Get plan items request
type GetPlanItemsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Filters       *PlanItemFilters       `protobuf:"bytes,1,opt,name=filters,proto3" json:"filters,omitempty"`
	ClientVersion *VersionInfo           `protobuf:"bytes,2,opt,name=client_version,json=clientVersion,proto3" json:"client_version,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPlanItemsRequest) Reset() {
	*x = GetPlanItemsRequest{}
	mi := &file_download_proto_musicdl_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPlanItemsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPlanItemsRequest) ProtoMessage() {}

func (x *GetPlanItemsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_download_proto_musicdl_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPlanItemsRequest.ProtoReflect.Descriptor instead.
func (*GetPlanItemsRequest) Descriptor() ([]byte, []int) {
	return file_download_proto_musicdl_proto_rawDescGZIP(), []int{13}
}

func (x *GetPlanItemsRequest) GetFilters() *PlanItemFilters {
	if x != nil {
		return x.Filters
	}
	return nil
}

func (x *GetPlanItemsRequest) GetClientVersion() *VersionInfo {
	if x != nil {
		return x.ClientVersion
	}
	return nil
}

// Get plan items response
type GetPlanItemsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Items         []*PlanItem            `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`
	ServerVersion *VersionInfo           `protobuf:"bytes,2,opt,name=server_version,json=serverVersion,proto3" json:"server_version,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPlanItemsResponse) Reset() {
	*x = GetPlanItemsResponse{}
	mi := &file_download_proto_musicdl_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPlanItemsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPlanItemsResponse) ProtoMessage() {}

func (x *GetPlanItemsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_download_proto_musicdl_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPlanItemsResponse.ProtoReflect.Descriptor instead.
func (*GetPlanItemsResponse) Descriptor() ([]byte, []int) {
	return file_download_proto_musicdl_proto_rawDescGZIP(), []int{14}
}

func (x *GetPlanItemsResponse) GetItems() []*PlanItem {
	if x != nil {
		return x.Items
	}
	return nil
}

func (x *GetPlanItemsResponse) GetServerVersion() *VersionInfo {
	if x != nil {
		return x.ServerVersion
	}
	return nil
}

// Stream logs request
type StreamLogsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Levels        []LogLevel             `protobuf:"varint,1,rep,packed,name=levels,proto3,enum=proto.LogLevel" json:"levels,omitempty"`
	StartTime     *int64                 `protobuf:"varint,2,opt,name=start_time,json=startTime,proto3,oneof" json:"start_time,omitempty"` // Unix timestamp, 0 for all
	EndTime       *int64                 `protobuf:"varint,3,opt,name=end_time,json=endTime,proto3,oneof" json:"end_time,omitempty"`       // Unix timestamp, 0 for all
	Search        string                 `protobuf:"bytes,4,opt,name=search,proto3" json:"search,omitempty"`                               // Search term
	Follow        bool                   `protobuf:"varint,5,opt,name=follow,proto3" json:"follow,omitempty"`                              // Follow new logs (tail -f)
	ClientVersion *VersionInfo           `protobuf:"bytes,6,opt,name=client_version,json=clientVersion,proto3" json:"client_version,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StreamLogsRequest) Reset() {
	*x = StreamLogsRequest{}
	mi := &file_download_proto_musicdl_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StreamLogsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StreamLogsRequest) ProtoMessage() {}

func (x *StreamLogsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_download_proto_musicdl_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StreamLogsRequest.ProtoReflect.Descriptor instead.
func (*StreamLogsRequest) Descriptor() ([]byte, []int) {
	return file_download_proto_musicdl_proto_rawDescGZIP(), []int{15}
}

func (x *StreamLogsRequest) GetLevels() []LogLevel {
	if x != nil {
		return x.Levels
	}
	return nil
}

func (x *StreamLogsRequest) GetStartTime() int64 {
	if x != nil && x.StartTime != nil {
		return *x.StartTime
	}
	return 0
}

func (x *StreamLogsRequest) GetEndTime() int64 {
	if x != nil && x.EndTime != nil {
		return *x.EndTime
	}
	return 0
}

func (x *StreamLogsRequest) GetSearch() string {
	if x != nil {
		return x.Search
	}
	return ""
}

func (x *StreamLogsRequest) GetFollow() bool {
	if x != nil {
		return x.Follow
	}
	return false
}

func (x *StreamLogsRequest) GetClientVersion() *VersionInfo {
	if x != nil {
		return x.ClientVersion
	}
	return nil
}

// Log entry
type LogEntry struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Timestamp     int64                  `protobuf:"varint,1,opt,name=timestamp,proto3" json:"timestamp,omitempty"` // Unix timestamp
	Level         LogLevel               `protobuf:"varint,2,opt,name=level,proto3,enum=proto.LogLevel" json:"level,omitempty"`
	Message       string                 `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
	Service       string                 `protobuf:"bytes,4,opt,name=service,proto3" json:"service,omitempty"`     // "web-server" or "download-service"
	Operation     string                 `protobuf:"bytes,5,opt,name=operation,proto3" json:"operation,omitempty"` // Optional operation name
	Error         string                 `protobuf:"bytes,6,opt,name=error,proto3" json:"error,omitempty"`         // Optional error details
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LogEntry) Reset() {
	*x = LogEntry{}
	mi := &file_download_proto_musicdl_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LogEntry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LogEntry) ProtoMessage() {}

func (x *LogEntry) ProtoReflect() protoreflect.Message {
	mi := &file_download_proto_musicdl_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LogEntry.ProtoReflect.Descriptor instead.
func (*LogEntry) Descriptor() ([]byte, []int) {
	return file_download_proto_musicdl_proto_rawDescGZIP(), []int{16}
}

func (x *LogEntry) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

func (x *LogEntry) GetLevel() LogLevel {
	if x != nil {
		return x.Level
	}
	return LogLevel_LOG_LEVEL_UNSPECIFIED
}

func (x *LogEntry) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *LogEntry) GetService() string {
	if x != nil {
		return x.Service
	}
	return ""
}

func (x *LogEntry) GetOperation() string {
	if x != nil {
		return x.Operation
	}
	return ""
}

func (x *LogEntry) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

// Validate config request
type ValidateConfigRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Config        *Config                `protobuf:"bytes,1,opt,name=config,proto3" json:"config,omitempty"`
	ClientVersion *VersionInfo           `protobuf:"bytes,2,opt,name=client_version,json=clientVersion,proto3" json:"client_version,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ValidateConfigRequest) Reset() {
	*x = ValidateConfigRequest{}
	mi := &file_download_proto_musicdl_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ValidateConfigRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ValidateConfigRequest) ProtoMessage() {}

func (x *ValidateConfigRequest) ProtoReflect() protoreflect.Message {
	mi := &file_download_proto_musicdl_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ValidateConfigRequest.ProtoReflect.Descriptor instead.
func (*ValidateConfigRequest) Descriptor() ([]byte, []int) {
	return file_download_proto_musicdl_proto_rawDescGZIP(), []int{17}
}

func (x *ValidateConfigRequest) GetConfig() *Config {
	if x != nil {
		return x.Config
	}
	return nil
}

func (x *ValidateConfigRequest) GetClientVersion() *VersionInfo {
	if x != nil {
		return x.ClientVersion
	}
	return nil
}

// Validation error
type ValidationError struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Field         string                 `protobuf:"bytes,1,opt,name=field,proto3" json:"field,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ValidationError) Reset() {
	*x = ValidationError{}
	mi := &file_download_proto_musicdl_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ValidationError) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ValidationError) ProtoMessage() {}

func (x *ValidationError) ProtoReflect() protoreflect.Message {
	mi := &file_download_proto_musicdl_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ValidationError.ProtoReflect.Descriptor instead.
func (*ValidationError) Descriptor() ([]byte, []int) {
	return file_download_proto_musicdl_proto_rawDescGZIP(), []int{18}
}

func (x *ValidationError) GetField() string {
	if x != nil {
		return x.Field
	}
	return ""
}

func (x *ValidationError) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

// Validation result
type ValidateConfigResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Valid         bool                   `protobuf:"varint,1,opt,name=valid,proto3" json:"valid,omitempty"`
	Errors        []*ValidationError     `protobuf:"bytes,2,rep,name=errors,proto3" json:"errors,omitempty"`
	Warnings      []string               `protobuf:"bytes,3,rep,name=warnings,proto3" json:"warnings,omitempty"`
	ServerVersion *VersionInfo           `protobuf:"bytes,4,opt,name=server_version,json=serverVersion,proto3" json:"server_version,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ValidateConfigResponse) Reset() {
	*x = ValidateConfigResponse{}
	mi := &file_download_proto_musicdl_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ValidateConfigResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ValidateConfigResponse) ProtoMessage() {}

func (x *ValidateConfigResponse) ProtoReflect() protoreflect.Message {
	mi := &file_download_proto_musicdl_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ValidateConfigResponse.ProtoReflect.Descriptor instead.
func (*ValidateConfigResponse) Descriptor() ([]byte, []int) {
	return file_download_proto_musicdl_proto_rawDescGZIP(), []int{19}
}

func (x *ValidateConfigResponse) GetValid() bool {
	if x != nil {
		return x.Valid
	}
	return false
}

func (x *ValidateConfigResponse) GetErrors() []*ValidationError {
	if x != nil {
		return x.Errors
	}
	return nil
}

func (x *ValidateConfigResponse) GetWarnings() []string {
	if x != nil {
		return x.Warnings
	}
	return nil
}

func (x *ValidateConfigResponse) GetServerVersion() *VersionInfo {
	if x != nil {
		return x.ServerVersion
	}
	return nil
}

// Health check request
type HealthCheckRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ClientVersion *VersionInfo           `protobuf:"bytes,1,opt,name=client_version,json=clientVersion,proto3" json:"client_version,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthCheckRequest) Reset() {
	*x = HealthCheckRequest{}
	mi := &file_download_proto_musicdl_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthCheckRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthCheckRequest) ProtoMessage() {}

func (x *HealthCheckRequest) ProtoReflect() protoreflect.Message {
	mi := &file_download_proto_musicdl_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthCheckRequest.ProtoReflect.Descriptor instead.
func (*HealthCheckRequest) Descriptor() ([]byte, []int) {
	return file_download_proto_musicdl_proto_rawDescGZIP(), []int{20}
}

func (x *HealthCheckRequest) GetClientVersion() *VersionInfo {
	if x != nil {
		return x.ClientVersion
	}
	return nil
}

// Health check response
type HealthCheckResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Liveness      HealthStatus           `protobuf:"varint,1,opt,name=liveness,proto3,enum=proto.HealthStatus" json:"liveness,omitempty"`
	Readiness     ReadinessStatus        `protobuf:"varint,2,opt,name=readiness,proto3,enum=proto.ReadinessStatus" json:"readiness,omitempty"`
	ServiceHealth HealthStatus           `protobuf:"varint,3,opt,name=service_health,json=serviceHealth,proto3,enum=proto.HealthStatus" json:"service_health,omitempty"`
	ServerVersion *VersionInfo           `protobuf:"bytes,4,opt,name=server_version,json=serverVersion,proto3" json:"server_version,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthCheckResponse) Reset() {
	*x = HealthCheckResponse{}
	mi := &file_download_proto_musicdl_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthCheckResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthCheckResponse) ProtoMessage() {}

func (x *HealthCheckResponse) ProtoReflect() protoreflect.Message {
	mi := &file_download_proto_musicdl_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthCheckResponse.ProtoReflect.Descriptor instead.
func (*HealthCheckResponse) Descriptor() ([]byte, []int) {
	return file_download_proto_musicdl_proto_rawDescGZIP(), []int{21}
}

func (x *HealthCheckResponse) GetLiveness() HealthStatus {
	if x != nil {
		return x.Liveness
	}
	return HealthStatus_HEALTH_STATUS_UNSPECIFIED
}

func (x *HealthCheckResponse) GetReadiness() ReadinessStatus {
	if x != nil {
		return x.Readiness
	}
	return ReadinessStatus_READINESS_STATUS_UNSPECIFIED
}

func (x *HealthCheckResponse) GetServiceHealth() HealthStatus {
	if x != nil {
		return x.ServiceHealth
	}
	return HealthStatus_HEALTH_STATUS_UNSPECIFIED
}

func (x *HealthCheckResponse) GetServerVersion() *VersionInfo {
	if x != nil {
		return x.ServerVersion
	}
	return nil
}

var File_download_proto_musicdl_proto protoreflect.FileDescriptor

const file_download_proto_musicdl_proto_rawDesc = "" +
	"\n" +
	"\x1cdownload/proto/musicdl.proto\x12\x05proto\"'\n" +
	"\vVersionInfo\x12\x18\n" +
	"\aversion\x18\x01 \x01(\tR\aversion\"R\n" +
	"\vMusicSource\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x10\n" +
	"\x03url\x18\x02 \x01(\tR\x03url\x12\x1d\n" +
	"\n" +
	"create_m3u\x18\x03 \x01(\bR\tcreateM3u\"\xe8\v\n" +
	"\x10DownloadSettings\x12\x1b\n" +
	"\tclient_id\x18\x01 \x01(\tR\bclientId\x12#\n" +
	"\rclient_secret\x18\x02 \x01(\tR\fclientSecret\x12\x18\n" +
	"\athreads\x18\x03 \x01(\x05R\athreads\x12\x1f\n" +
	"\vmax_retries\x18\x04 \x01(\x05R\n" +
	"maxRetries\x12\x16\n" +
	"\x06format\x18\x05 \x01(\tR\x06format\x12\x18\n" +
	"\abitrate\x18\x06 \x01(\tR\abitrate\x12\x16\n" +
	"\x06output\x18\a \x01(\tR\x06output\x12'\n" +
	"\x0faudio_providers\x18\b \x03(\tR\x0eaudioProviders\x12\x1c\n" +
	"\toverwrite\x18\t \x01(\tR\toverwrite\x12$\n" +
	"\x0ecache_max_size\x18\n" +
	" \x01(\x05R\fcacheMaxSize\x12\x1b\n" +
	"\tcache_ttl\x18\v \x01(\x05R\bcacheTtl\x12<\n" +
	"\x1baudio_search_cache_max_size\x18\f \x01(\x05R\x17audioSearchCacheMaxSize\x123\n" +
	"\x16audio_search_cache_ttl\x18\r \x01(\x05R\x13audioSearchCacheTtl\x12@\n" +
	"\x1dfile_existence_cache_max_size\x18\x0e \x01(\x05R\x19fileExistenceCacheMaxSize\x127\n" +
	"\x18file_existence_cache_ttl\x18\x0f \x01(\x05R\x15fileExistenceCacheTtl\x12.\n" +
	"\x13spotify_max_retries\x18\x10 \x01(\x05R\x11spotifyMaxRetries\x127\n" +
	"\x18spotify_retry_base_delay\x18\x11 \x01(\x01R\x15spotifyRetryBaseDelay\x125\n" +
	"\x17spotify_retry_max_delay\x18\x12 \x01(\x01R\x14spotifyRetryMaxDelay\x12;\n" +
	"\x1aspotify_rate_limit_enabled\x18\x13 \x01(\bR\x17spotifyRateLimitEnabled\x12=\n" +
	"\x1bspotify_rate_limit_requests\x18\x14 \x01(\x05R\x18spotifyRateLimitRequests\x129\n" +
	"\x19spotify_rate_limit_window\x18\x15 \x01(\x01R\x16spotifyRateLimitWindow\x12=\n" +
	"\x1bdownload_rate_limit_enabled\x18\x16 \x01(\bR\x18downloadRateLimitEnabled\x12?\n" +
	"\x1cdownload_rate_limit_requests\x18\x17 \x01(\x05R\x19downloadRateLimitRequests\x12;\n" +
	"\x1adownload_rate_limit_window\x18\x18 \x01(\x01R\x17downloadRateLimitWindow\x12=\n" +
	"\x18download_bandwidth_limit\x18\x19 \x01(\x05H\x00R\x16downloadBandwidthLimit\x88\x01\x01\x126\n" +
	"\x17plan_generation_enabled\x18\x1a \x01(\bR\x15planGenerationEnabled\x12:\n" +
	"\x19plan_optimization_enabled\x18\x1b \x01(\bR\x17planOptimizationEnabled\x124\n" +
	"\x16plan_execution_enabled\x18\x1c \x01(\bR\x14planExecutionEnabled\x128\n" +
	"\x18plan_persistence_enabled\x18\x1d \x01(\bR\x16planPersistenceEnabled\x12A\n" +
	"\x1dplan_status_reporting_enabled\x18\x1e \x01(\bR\x1aplanStatusReportingEnabledB\x1b\n" +
	"\x19_download_bandwidth_limit\"\xa4\x01\n" +
	"\n" +
	"UISettings\x12!\n" +
	"\fhistory_path\x18\x01 \x01(\tR\vhistoryPath\x12+\n" +
	"\x11history_retention\x18\x02 \x01(\x05R\x10historyRetention\x12+\n" +
	"\x11snapshot_interval\x18\x03 \x01(\x05R\x10snapshotInterval\x12\x19\n" +
	"\blog_path\x18\x04 \x01(\tR\alogPath\"\xb0\x02\n" +
	"\x06Config\x12\x18\n" +
	"\aversion\x18\x01 \x01(\tR\aversion\x123\n" +
	"\bdownload\x18\x02 \x01(\v2\x17.proto.DownloadSettingsR\bdownload\x12!\n" +
	"\x02ui\x18\x03 \x01(\v2\x11.proto.UISettingsR\x02ui\x12(\n" +
	"\x05songs\x18\x04 \x03(\v2\x12.proto.MusicSourceR\x05songs\x12,\n" +
	"\aartists\x18\x05 \x03(\v2\x12.proto.MusicSourceR\aartists\x120\n" +
	"\tplaylists\x18\x06 \x03(\v2\x12.proto.MusicSourceR\tplaylists\x12*\n" +
	"\x06albums\x18\a \x03(\v2\x12.proto.MusicSourceR\x06albums\"\x85\x05\n" +
	"\bPlanItem\x12\x17\n" +
	"\aitem_id\x18\x01 \x01(\tR\x06itemId\x120\n" +
	"\titem_type\x18\x02 \x01(\x0e2\x13.proto.PlanItemTypeR\bitemType\x12\x1d\n" +
	"\n" +
	"spotify_id\x18\x03 \x01(\tR\tspotifyId\x12\x1f\n" +
	"\vspotify_url\x18\x04 \x01(\tR\n" +
	"spotifyUrl\x12\x1f\n" +
	"\vyoutube_url\x18\x05 \x01(\tR\n" +
	"youtubeUrl\x12\x1b\n" +
	"\tparent_id\x18\x06 \x01(\tR\bparentId\x12\x1b\n" +
	"\tchild_ids\x18\a \x03(\tR\bchildIds\x12\x12\n" +
	"\x04name\x18\b \x01(\tR\x04name\x129\n" +
	"\bmetadata\x18\t \x03(\v2\x1d.proto.PlanItem.MetadataEntryR\bmetadata\x12-\n" +
	"\x06status\x18\n" +
	" \x01(\x0e2\x15.proto.PlanItemStatusR\x06status\x12\x14\n" +
	"\x05error\x18\v \x01(\tR\x05error\x12\x1b\n" +
	"\tfile_path\x18\f \x01(\tR\bfilePath\x12\x1d\n" +
	"\n" +
	"created_at\x18\r \x01(\x03R\tcreatedAt\x12\"\n" +
	"\n" +
	"started_at\x18\x0e \x01(\x03H\x00R\tstartedAt\x88\x01\x01\x12&\n" +
	"\fcompleted_at\x18\x0f \x01(\x03H\x01R\vcompletedAt\x88\x01\x01\x12\x1a\n" +
	"\bprogress\x18\x10 \x01(\x01R\bprogress\x1a;\n" +
	"\rMetadataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01B\r\n" +
	"\v_started_atB\x0f\n" +
	"\r_completed_at\"\xb0\x01\n" +
	"\x14StartDownloadRequest\x12%\n" +
	"\x06config\x18\x01 \x01(\v2\r.proto.ConfigR\x06config\x12\x1b\n" +
	"\tplan_path\x18\x02 \x01(\tR\bplanPath\x12\x19\n" +
	"\blog_path\x18\x03 \x01(\tR\alogPath\x129\n" +
	"\x0eclient_version\x18\x04 \x01(\v2\x12.proto.VersionInfoR\rclientVersion\"\x91\x01\n" +
	"\x15StartDownloadResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12#\n" +
	"\rerror_message\x18\x02 \x01(\tR\ferrorMessage\x129\n" +
	"\x0eserver_version\x18\x03 \x01(\v2\x12.proto.VersionInfoR\rserverVersion\"P\n" +
	"\x13StopDownloadRequest\x129\n" +
	"\x0eclient_version\x18\x01 \x01(\v2\x12.proto.VersionInfoR\rclientVersion\"\x90\x01\n" +
	"\x14StopDownloadResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12#\n" +
	"\rerror_message\x18\x02 \x01(\tR\ferrorMessage\x129\n" +
	"\x0eserver_version\x18\x03 \x01(\v2\x12.proto.VersionInfoR\rserverVersion\"M\n" +
	"\x10GetStatusRequest\x129\n" +
	"\x0eclient_version\x18\x01 \x01(\v2\x12.proto.VersionInfoR\rclientVersion\"\x90\x04\n" +
	"\x11GetStatusResponse\x12)\n" +
	"\x05state\x18\x01 \x01(\x0e2\x13.proto.ServiceStateR\x05state\x12)\n" +
	"\x05phase\x18\x02 \x01(\x0e2\x13.proto.ServicePhaseR\x05phase\x12#\n" +
	"\rerror_message\x18\x03 \x01(\tR\ferrorMessage\x12\x1d\n" +
	"\n" +
	"started_at\x18\x04 \x01(\x03R\tstartedAt\x12&\n" +
	"\fcompleted_at\x18\x05 \x01(\x03H\x00R\vcompletedAt\x88\x01\x01\x12/\n" +
	"\x13progress_percentage\x18\x06 \x01(\x01R\x12progressPercentage\x12\x1f\n" +
	"\vtotal_items\x18\a \x01(\x05R\n" +
	"totalItems\x12'\n" +
	"\x0fcompleted_items\x18\b \x01(\x05R\x0ecompletedItems\x12!\n" +
	"\ffailed_items\x18\t \x01(\x05R\vfailedItems\x12#\n" +
	"\rpending_items\x18\n" +
	" \x01(\x05R\fpendingItems\x12*\n" +
	"\x11in_progress_items\x18\v \x01(\x05R\x0finProgressItems\x129\n" +
	"\x0eserver_version\x18\f \x01(\v2\x12.proto.VersionInfoR\rserverVersionB\x0f\n" +
	"\r_completed_at\"\x81\x01\n" +
	"\x0fPlanItemFilters\x12-\n" +
	"\x06status\x18\x01 \x03(\x0e2\x15.proto.PlanItemStatusR\x06status\x12'\n" +
	"\x04type\x18\x02 \x03(\x0e2\x13.proto.PlanItemTypeR\x04type\x12\x16\n" +
	"\x06search\x18\x03 \x01(\tR\x06search\"\x82\x01\n" +
	"\x13GetPlanItemsRequest\x120\n" +
	"\afilters\x18\x01 \x01(\v2\x16.proto.PlanItemFiltersR\afilters\x129\n" +
	"\x0eclient_version\x18\x02 \x01(\v2\x12.proto.VersionInfoR\rclientVersion\"x\n" +
	"\x14GetPlanItemsResponse\x12%\n" +
	"\x05items\x18\x01 \x03(\v2\x0f.proto.PlanItemR\x05items\x129\n" +
	"\x0eserver_version\x18\x02 \x01(\v2\x12.proto.VersionInfoR\rserverVersion\"\x87\x02\n" +
	"\x11StreamLogsRequest\x12'\n" +
	"\x06levels\x18\x01 \x03(\x0e2\x0f.proto.LogLevelR\x06levels\x12\"\n" +
	"\n" +
	"start_time\x18\x02 \x01(\x03H\x00R\tstartTime\x88\x01\x01\x12\x1e\n" +
	"\bend_time\x18\x03 \x01(\x03H\x01R\aendTime\x88\x01\x01\x12\x16\n" +
	"\x06search\x18\x04 \x01(\tR\x06search\x12\x16\n" +
	"\x06follow\x18\x05 \x01(\bR\x06follow\x129\n" +
	"\x0eclient_version\x18\x06 \x01(\v2\x12.proto.VersionInfoR\rclientVersionB\r\n" +
	"\v_start_timeB\v\n" +
	"\t_end_time\"\xb7\x01\n" +
	"\bLogEntry\x12\x1c\n" +
	"\ttimestamp\x18\x01 \x01(\x03R\ttimestamp\x12%\n" +
	"\x05level\x18\x02 \x01(\x0e2\x0f.proto.LogLevelR\x05level\x12\x18\n" +
	"\amessage\x18\x03 \x01(\tR\amessage\x12\x18\n" +
	"\aservice\x18\x04 \x01(\tR\aservice\x12\x1c\n" +
	"\toperation\x18\x05 \x01(\tR\toperation\x12\x14\n" +
	"\x05error\x18\x06 \x01(\tR\x05error\"y\n" +
	"\x15ValidateConfigRequest\x12%\n" +
	"\x06config\x18\x01 \x01(\v2\r.proto.ConfigR\x06config\x129\n" +
	"\x0eclient_version\x18\x02 \x01(\v2\x12.proto.VersionInfoR\rclientVersion\"A\n" +
	"\x0fValidationError\x12\x14\n" +
	"\x05field\x18\x01 \x01(\tR\x05field\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"\xb5\x01\n" +
	"\x16ValidateConfigResponse\x12\x14\n" +
	"\x05valid\x18\x01 \x01(\bR\x05valid\x12.\n" +
	"\x06errors\x18\x02 \x03(\v2\x16.proto.ValidationErrorR\x06errors\x12\x1a\n" +
	"\bwarnings\x18\x03 \x03(\tR\bwarnings\x129\n" +
	"\x0eserver_version\x18\x04 \x01(\v2\x12.proto.VersionInfoR\rserverVersion\"O\n" +
	"\x12HealthCheckRequest\x129\n" +
	"\x0eclient_version\x18\x01 \x01(\v2\x12.proto.VersionInfoR\rclientVersion\"\xf3\x01\n" +
	"\x13HealthCheckResponse\x12/\n" +
	"\bliveness\x18\x01 \x01(\x0e2\x13.proto.HealthStatusR\bliveness\x124\n" +
	"\treadiness\x18\x02 \x01(\x0e2\x16.proto.ReadinessStatusR\treadiness\x12:\n" +
	"\x0eservice_health\x18\x03 \x01(\x0e2\x13.proto.HealthStatusR\rserviceHealth\x129\n" +
	"\x0eserver_version\x18\x04 \x01(\v2\x12.proto.VersionInfoR\rserverVersion*\xb2\x01\n" +
	"\fPlanItemType\x12\x1e\n" +
	"\x1aPLAN_ITEM_TYPE_UNSPECIFIED\x10\x00\x12\x18\n" +
	"\x14PLAN_ITEM_TYPE_TRACK\x10\x01\x12\x18\n" +
	"\x14PLAN_ITEM_TYPE_ALBUM\x10\x02\x12\x19\n" +
	"\x15PLAN_ITEM_TYPE_ARTIST\x10\x03\x12\x1b\n" +
	"\x17PLAN_ITEM_TYPE_PLAYLIST\x10\x04\x12\x16\n" +
	"\x12PLAN_ITEM_TYPE_M3U\x10\x05*\xcd\x01\n" +
	"\x0ePlanItemStatus\x12 \n" +
	"\x1cPLAN_ITEM_STATUS_UNSPECIFIED\x10\x00\x12\x1c\n" +
	"\x18PLAN_ITEM_STATUS_PENDING\x10\x01\x12 \n" +
	"\x1cPLAN_ITEM_STATUS_IN_PROGRESS\x10\x02\x12\x1e\n" +
	"\x1aPLAN_ITEM_STATUS_COMPLETED\x10\x03\x12\x1b\n" +
	"\x17PLAN_ITEM_STATUS_FAILED\x10\x04\x12\x1c\n" +
	"\x18PLAN_ITEM_STATUS_SKIPPED\x10\x05*\x95\x01\n" +
	"\fServiceState\x12\x1d\n" +
	"\x19SERVICE_STATE_UNSPECIFIED\x10\x00\x12\x16\n" +
	"\x12SERVICE_STATE_IDLE\x10\x01\x12\x19\n" +
	"\x15SERVICE_STATE_RUNNING\x10\x02\x12\x1a\n" +
	"\x16SERVICE_STATE_STOPPING\x10\x03\x12\x17\n" +
	"\x13SERVICE_STATE_ERROR\x10\x04*\xd4\x01\n" +
	"\fServicePhase\x12\x1d\n" +
	"\x19SERVICE_PHASE_UNSPECIFIED\x10\x00\x12\x16\n" +
	"\x12SERVICE_PHASE_IDLE\x10\x01\x12\x1c\n" +
	"\x18SERVICE_PHASE_GENERATING\x10\x02\x12\x1c\n" +
	"\x18SERVICE_PHASE_OPTIMIZING\x10\x03\x12\x1b\n" +
	"\x17SERVICE_PHASE_EXECUTING\x10\x04\x12\x1b\n" +
	"\x17SERVICE_PHASE_COMPLETED\x10\x05\x12\x17\n" +
	"\x13SERVICE_PHASE_ERROR\x10\x06*\x84\x01\n" +
	"\fHealthStatus\x12\x1d\n" +
	"\x19HEALTH_STATUS_UNSPECIFIED\x10\x00\x12\x19\n" +
	"\x15HEALTH_STATUS_HEALTHY\x10\x01\x12\x1b\n" +
	"\x17HEALTH_STATUS_UNHEALTHY\x10\x02\x12\x1d\n" +
	"\x19HEALTH_STATUS_UNAVAILABLE\x10\x03*\x91\x01\n" +
	"\x0fReadinessStatus\x12 \n" +
	"\x1cREADINESS_STATUS_UNSPECIFIED\x10\x00\x12\x1a\n" +
	"\x16READINESS_STATUS_READY\x10\x01\x12\x1e\n" +
	"\x1aREADINESS_STATUS_NOT_READY\x10\x02\x12 \n" +
	"\x1cREADINESS_STATUS_UNAVAILABLE\x10\x03*w\n" +
	"\bLogLevel\x12\x19\n" +
	"\x15LOG_LEVEL_UNSPECIFIED\x10\x00\x12\x13\n" +
	"\x0fLOG_LEVEL_DEBUG\x10\x01\x12\x12\n" +
	"\x0eLOG_LEVEL_INFO\x10\x02\x12\x12\n" +
	"\x0eLOG_LEVEL_WARN\x10\x03\x12\x13\n" +
	"\x0fLOG_LEVEL_ERROR\x10\x042\xff\x03\n" +
	"\x0fDownloadService\x12J\n" +
	"\rStartDownload\x12\x1b.proto.StartDownloadRequest\x1a\x1c.proto.StartDownloadResponse\x12G\n" +
	"\fStopDownload\x12\x1a.proto.StopDownloadRequest\x1a\x1b.proto.StopDownloadResponse\x12>\n" +
	"\tGetStatus\x12\x17.proto.GetStatusRequest\x1a\x18.proto.GetStatusResponse\x12G\n" +
	"\fGetPlanItems\x12\x1a.proto.GetPlanItemsRequest\x1a\x1b.proto.GetPlanItemsResponse\x129\n" +
	"\n" +
	"StreamLogs\x12\x18.proto.StreamLogsRequest\x1a\x0f.proto.LogEntry0\x01\x12M\n" +
	"\x0eValidateConfig\x12\x1c.proto.ValidateConfigRequest\x1a\x1d.proto.ValidateConfigResponse\x12D\n" +
	"\vHealthCheck\x12\x19.proto.HealthCheckRequest\x1a\x1a.proto.HealthCheckResponseB(Z&github.com/sv4u/musicdl/download/protob\x06proto3"

var (
	file_download_proto_musicdl_proto_rawDescOnce sync.Once
	file_download_proto_musicdl_proto_rawDescData []byte
)

func file_download_proto_musicdl_proto_rawDescGZIP() []byte {
	file_download_proto_musicdl_proto_rawDescOnce.Do(func() {
		file_download_proto_musicdl_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_download_proto_musicdl_proto_rawDesc), len(file_download_proto_musicdl_proto_rawDesc)))
	})
	return file_download_proto_musicdl_proto_rawDescData
}

var file_download_proto_musicdl_proto_enumTypes = make([]protoimpl.EnumInfo, 7)
var file_download_proto_musicdl_proto_msgTypes = make([]protoimpl.MessageInfo, 23)
var file_download_proto_musicdl_proto_goTypes = []any{
	(PlanItemType)(0),              // 0: proto.PlanItemType
	(PlanItemStatus)(0),            // 1: proto.PlanItemStatus
	(ServiceState)(0),              // 2: proto.ServiceState
	(ServicePhase)(0),              // 3: proto.ServicePhase
	(HealthStatus)(0),              // 4: proto.HealthStatus
	(ReadinessStatus)(0),           // 5: proto.ReadinessStatus
	(LogLevel)(0),                  // 6: proto.LogLevel
	(*VersionInfo)(nil),            // 7: proto.VersionInfo
	(*MusicSource)(nil),            // 8: proto.MusicSource
	(*DownloadSettings)(nil),       // 9: proto.DownloadSettings
	(*UISettings)(nil),             // 10: proto.UISettings
	(*Config)(nil),                 // 11: proto.Config
	(*PlanItem)(nil),               // 12: proto.PlanItem
	(*StartDownloadRequest)(nil),   // 13: proto.StartDownloadRequest
	(*StartDownloadResponse)(nil),  // 14: proto.StartDownloadResponse
	(*StopDownloadRequest)(nil),    // 15: proto.StopDownloadRequest
	(*StopDownloadResponse)(nil),   // 16: proto.StopDownloadResponse
	(*GetStatusRequest)(nil),       // 17: proto.GetStatusRequest
	(*GetStatusResponse)(nil),      // 18: proto.GetStatusResponse
	(*PlanItemFilters)(nil),        // 19: proto.PlanItemFilters
	(*GetPlanItemsRequest)(nil),    // 20: proto.GetPlanItemsRequest
	(*GetPlanItemsResponse)(nil),   // 21: proto.GetPlanItemsResponse
	(*StreamLogsRequest)(nil),      // 22: proto.StreamLogsRequest
	(*LogEntry)(nil),               // 23: proto.LogEntry
	(*ValidateConfigRequest)(nil),  // 24: proto.ValidateConfigRequest
	(*ValidationError)(nil),        // 25: proto.ValidationError
	(*ValidateConfigResponse)(nil), // 26: proto.ValidateConfigResponse
	(*HealthCheckRequest)(nil),     // 27: proto.HealthCheckRequest
	(*HealthCheckResponse)(nil),    // 28: proto.HealthCheckResponse
	nil,                            // 29: proto.PlanItem.MetadataEntry
}
var file_download_proto_musicdl_proto_depIdxs = []int32{
	9,  // 0: proto.Config.download:type_name -> proto.DownloadSettings
	10, // 1: proto.Config.ui:type_name -> proto.UISettings
	8,  // 2: proto.Config.songs:type_name -> proto.MusicSource
	8,  // 3: proto.Config.artists:type_name -> proto.MusicSource
	8,  // 4: proto.Config.playlists:type_name -> proto.MusicSource
	8,  // 5: proto.Config.albums:type_name -> proto.MusicSource
	0,  // 6: proto.PlanItem.item_type:type_name -> proto.PlanItemType
	29, // 7: proto.PlanItem.metadata:type_name -> proto.PlanItem.MetadataEntry
	1,  // 8: proto.PlanItem.status:type_name -> proto.PlanItemStatus
	11, // 9: proto.StartDownloadRequest.config:type_name -> proto.Config
	7,  // 10: proto.StartDownloadRequest.client_version:type_name -> proto.VersionInfo
	7,  // 11: proto.StartDownloadResponse.server_version:type_name -> proto.VersionInfo
	7,  // 12: proto.StopDownloadRequest.client_version:type_name -> proto.VersionInfo
	7,  // 13: proto.StopDownloadResponse.server_version:type_name -> proto.VersionInfo
	7,  // 14: proto.GetStatusRequest.client_version:type_name -> proto.VersionInfo
	2,  // 15: proto.GetStatusResponse.state:type_name -> proto.ServiceState
	3,  // 16: proto.GetStatusResponse.phase:type_name -> proto.ServicePhase
	7,  // 17: proto.GetStatusResponse.server_version:type_name -> proto.VersionInfo
	1,  // 18: proto.PlanItemFilters.status:type_name -> proto.PlanItemStatus
	0,  // 19: proto.PlanItemFilters.type:type_name -> proto.PlanItemType
	19, // 20: proto.GetPlanItemsRequest.filters:type_name -> proto.PlanItemFilters
	7,  // 21: proto.GetPlanItemsRequest.client_version:type_name -> proto.VersionInfo
	12, // 22: proto.GetPlanItemsResponse.items:type_name -> proto.PlanItem
	7,  // 23: proto.GetPlanItemsResponse.server_version:type_name -> proto.VersionInfo
	6,  // 24: proto.StreamLogsRequest.levels:type_name -> proto.LogLevel
	7,  // 25: proto.StreamLogsRequest.client_version:type_name -> proto.VersionInfo
	6,  // 26: proto.LogEntry.level:type_name -> proto.LogLevel
	11, // 27: proto.ValidateConfigRequest.config:type_name -> proto.Config
	7,  // 28: proto.ValidateConfigRequest.client_version:type_name -> proto.VersionInfo
	25, // 29: proto.ValidateConfigResponse.errors:type_name -> proto.ValidationError
	7,  // 30: proto.ValidateConfigResponse.server_version:type_name -> proto.VersionInfo
	7,  // 31: proto.HealthCheckRequest.client_version:type_name -> proto.VersionInfo
	4,  // 32: proto.HealthCheckResponse.liveness:type_name -> proto.HealthStatus
	5,  // 33: proto.HealthCheckResponse.readiness:type_name -> proto.ReadinessStatus
	4,  // 34: proto.HealthCheckResponse.service_health:type_name -> proto.HealthStatus
	7,  // 35: proto.HealthCheckResponse.server_version:type_name -> proto.VersionInfo
	13, // 36: proto.DownloadService.StartDownload:input_type -> proto.StartDownloadRequest
	15, // 37: proto.DownloadService.StopDownload:input_type -> proto.StopDownloadRequest
	17, // 38: proto.DownloadService.GetStatus:input_type -> proto.GetStatusRequest
	20, // 39: proto.DownloadService.GetPlanItems:input_type -> proto.GetPlanItemsRequest
	22, // 40: proto.DownloadService.StreamLogs:input_type -> proto.StreamLogsRequest
	24, // 41: proto.DownloadService.ValidateConfig:input_type -> proto.ValidateConfigRequest
	27, // 42: proto.DownloadService.HealthCheck:input_type -> proto.HealthCheckRequest
	14, // 43: proto.DownloadService.StartDownload:output_type -> proto.StartDownloadResponse
	16, // 44: proto.DownloadService.StopDownload:output_type -> proto.StopDownloadResponse
	18, // 45: proto.DownloadService.GetStatus:output_type -> proto.GetStatusResponse
	21, // 46: proto.DownloadService.GetPlanItems:output_type -> proto.GetPlanItemsResponse
	23, // 47: proto.DownloadService.StreamLogs:output_type -> proto.LogEntry
	26, // 48: proto.DownloadService.ValidateConfig:output_type -> proto.ValidateConfigResponse
	28, // 49: proto.DownloadService.HealthCheck:output_type -> proto.HealthCheckResponse
	43, // [43:50] is the sub-list for method output_type
	36, // [36:43] is the sub-list for method input_type
	36, // [36:36] is the sub-list for extension type_name
	36, // [36:36] is the sub-list for extension extendee
	0,  // [0:36] is the sub-list for field type_name
}

func init() { file_download_proto_musicdl_proto_init() }
func file_download_proto_musicdl_proto_init() {
	if File_download_proto_musicdl_proto != nil {
		return
	}
	file_download_proto_musicdl_proto_msgTypes[2].OneofWrappers = []any{}
	file_download_proto_musicdl_proto_msgTypes[5].OneofWrappers = []any{}
	file_download_proto_musicdl_proto_msgTypes[11].OneofWrappers = []any{}
	file_download_proto_musicdl_proto_msgTypes[15].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_download_proto_musicdl_proto_rawDesc), len(file_download_proto_musicdl_proto_rawDesc)),
			NumEnums:      7,
			NumMessages:   23,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_download_proto_musicdl_proto_goTypes,
		DependencyIndexes: file_download_proto_musicdl_proto_depIdxs,
		EnumInfos:         file_download_proto_musicdl_proto_enumTypes,
		MessageInfos:      file_download_proto_musicdl_proto_msgTypes,
	}.Build()
	File_download_proto_musicdl_proto = out.File
	file_download_proto_musicdl_proto_goTypes = nil
	file_download_proto_musicdl_proto_depIdxs = nil
}
